// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBis_6mRBbIyTgx1VHROjRUli-lvBcK-oI',
    appId: '1:146552258367:web:7243d5eb7fcfde3c0f5d8a',
    messagingSenderId: '146552258367',
    projectId: 'confident-app-51348',
    authDomain: 'confident-app-51348.firebaseapp.com',
    storageBucket: 'confident-app-51348.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvWhztg0lz6kfrU9FZQPiPhLyacVE4_9k',
    appId: '1:146552258367:android:c9b8fa71d114a8b80f5d8a',
    messagingSenderId: '146552258367',
    projectId: 'confident-app-51348',
    storageBucket: 'confident-app-51348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD860imX_fu2Ok8_yWKExSLICCozavIriI',
    appId: '1:146552258367:ios:5eb2d9c542ef3c6a0f5d8a',
    messagingSenderId: '146552258367',
    projectId: 'confident-app-51348',
    storageBucket: 'confident-app-51348.appspot.com',
    iosClientId: '146552258367-74dh7qhmkl2sl0boo5k7mtnehppss4up.apps.googleusercontent.com',
    iosBundleId: 'com.example.confidentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD860imX_fu2Ok8_yWKExSLICCozavIriI',
    appId: '1:146552258367:ios:5eb2d9c542ef3c6a0f5d8a',
    messagingSenderId: '146552258367',
    projectId: 'confident-app-51348',
    storageBucket: 'confident-app-51348.appspot.com',
    iosClientId: '146552258367-74dh7qhmkl2sl0boo5k7mtnehppss4up.apps.googleusercontent.com',
    iosBundleId: 'com.example.confidentapp',
  );
}
